### ISSUE TITLE
What is a ‘state machine’?

### ISSUE THREAD

**Issue by wijohnst** [wijohnst/AnswerTheseQuestions#27]
[context](https://medium.com/serverless-transformation/what-a-typical-100-serverless-architecture-looks-like-in-aws-40f252cd0ecb)

**Comment by bark-barry** [comment]
A state machine is an object that keeps track of it's state and states that it is allowed to move to from a given state.  

As an example if I have a car, I can start the car if it's off.  Once it's on I can't tell the car to start again because it's already started.  And I can put it in drive if it's started, but if it's off and I try to tell it to drive it will reject that command because it's not in the right state to do so.
